---
# The cp_name property is a label to identify the Challenge Project (CP).
cp_name: nginx

# The language property denotes the *primary* language of the CP.
# CP Vulnerabilities (CPVs) that are eligible for points are found in the given
# language. Valid values for the AIxCC ASC are: 'c' and 'java'.
language: c

# The cp_sources property denotes the source repository addresses, as well
# as the local path that the repository resides starting from `./src`.
# The "ref" element is optional. It indicates the git repository
# tag or commit that should be checked out. If not specified, it will default
# to checking out the "main" branch of the specified repo from "address".
# The "artifacts" element is a list or sequence of the relevant build artifacts
# associated with the repository.
cp_sources:
    nginx:
        address: https://github.com/aixcc-public/challenge-004-nginx-source.git
        ref: hg-asc-v2.0.0
        artifacts:
            - src/nginx/objs/nginx

# The docker_image property denotes the address to pull the pre-built Docker
# image for the CP.
docker_image: ghcr.io/aixcc-public/challenge-004-nginx-cp

# The sanitizers property denotes which sanitizers are available for scoring for
# the CP. When specifying a sanitizer ID to the scoring server, use the *key*
# value, e.g. use "id_1", not "sanitizer string 1".
#
# Note, these key-value mappings are unique for each CP.
sanitizers:
    id_1: "AddressSanitizer: SEGV"
    id_2: "AddressSanitizer: heap-buffer-overflow"
    id_3: "AddressSanitizer: attempting double-free"
    id_4: "AddressSanitizer: heap-use-after-free"
    id_5: "AddressSanitizer: global-buffer-overflow"

# The harnesses property denotes which AIxCC harnesses are available to use for
# triggering sanitizers for the CP. When specifying a harness ID  to the
# scoring server, use the *key* value, e.g. "id_1", not the values under
# 'name', 'source', or 'binary'.
#
# The 'source' and 'binary' properties point the to the appropriate file for
# the harness source code and executable binary (if they exists). The 'name'
# string must be provided in the argument list when invoking
# `run.sh run_pov <args>`.
harnesses:
    id_1:
        name: mail_request_harness
        source: src/harnesses/mail_request_harness.cc
        binary: out/mail_request_harness
    id_2:
        name: pov_harness
        source: src/harnesses/pov_harness.cc
        binary: out/pov_harness
    id_3:
        name: smtp_harness
        source: src/harnesses/smtp_harness.cc
        binary: out/smtp_harness
